### ISSUE TITLE
signatory-cli list cli to display both errored keys along with non-errored keys

### ISSUE THREAD

**Issue by AbineshECAD** [ecadlabs/signatory#140]
ListPublicKeys API in pkg/signatory.go to returns error even when 1 of the many keys in the list fails when retrieved and processed.
Modify this generic code to display keys with failures on retrieval/decoding at the end after the success keys.

**Comment by danielelisi** [comment]
I just experienced this problem while testing AWS KMS vault from #143

One of the keys in my KMS store isn't recognized and Signatory crashes without returning the rest of the keys 
```
[{"id":"failure","kind":"temporary","msg":"tezos: unknown curve: P-384"}]
```

I believe it would be more appropriate to let the user specify which key ids to query instead of looping trough all keys in the KMS store.

**Comment by AbineshECAD** [comment]
Fix committed as part of https://github.com/ecadlabs/signatory/pull/143
